name: release
on:
  push:
    branches:
      - master

jobs:
  stable:
    permissions:
      contents: write
      id-token: write
      packages: write
      issues: write
      pull-requests: write
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
    with:
      createGithubReleases: true
      releaseScript: release
      nodeVersion: 22
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}
